const GET_CHARACTERS = 'GET_CHARACTERS'
const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS'
const GET_CHARACTERS_FAILURE = 'GET_CHARACTERS_FAILURE'

export {
  GET_CHARACTERS, GET_CHARACTERS_SUCCESS, GET_CHARACTERS_FAILURE
}
